import { useState, useEffect } from 'react';
import { useLocation } from 'react-router-dom';
import jsPDF from 'jspdf';
import 'jspdf-autotable';

export default function AdminSettings() {
  const location = useLocation();
  const [activeTab, setActiveTab] = useState('profile');
  const [loading, setLoading] = useState(false);
  const [showEditProfile, setShowEditProfile] = useState(false);
  
  useEffect(() => {
    const params = new URLSearchParams(location.search);
    const tab = params.get('tab');
    if (tab) setActiveTab(tab);
    
    // Load persisted theme
    const savedTheme = localStorage.getItem('admin_theme');
    if (savedTheme === 'dark') document.body.classList.add('dark-theme');
  }, [location]);

  // Tab: Profile Data (using localStorage for dummy persistence)
  const [profile, setProfile] = useState(() => {
    const saved = localStorage.getItem('admin_profile');
    return saved ? JSON.parse(saved) : {
      name: 'Admin User',
      username: 'admin',
      email: 'admin@smartcity.com',
      phone: '+91 98765 43210',
      role: 'Administrator',
      dept: 'Smart City Operations',
      empId: 'EMP-001',
      joined: 'January 10, 2024',
      lastLogin: 'April 25, 2026 — 10:30 AM',
      status: 'Active'
    };
  });

  const [editForm, setEditForm] = useState({ ...profile });

  // Tab: Account Settings
  const [settings, setSettings] = useState(() => {
    const saved = localStorage.getItem('admin_settings');
    return saved ? JSON.parse(saved) : {
      lang: 'English',
      timezone: 'IST — Asia/Kolkata (UTC +5:30)',
      dateFormat: 'DD/MM/YYYY',
      notifications: true,
      emailAlerts: true,
      smsAlerts: false,
      twoFactor: false,
      theme: 'light',
      timeout: '30 Minutes'
    };
  });

  const handleSaveProfile = () => {
    setLoading(true);
    setTimeout(() => {
      setProfile(editForm);
      localStorage.setItem('admin_profile', JSON.stringify(editForm));
      localStorage.setItem('username', editForm.name); // Update navbar
      setShowEditProfile(false);
      setLoading(false);
      alert('Profile updated successfully');
    }, 800);
  };

  const handleSaveSettings = () => {
    setLoading(true);
    setTimeout(() => {
      localStorage.setItem('admin_settings', JSON.stringify(settings));
      setLoading(false);
      alert('Account settings saved successfully');
    }, 800);
  };

  const toggleTheme = (mode) => {
    setSettings({ ...settings, theme: mode });
    if (mode === 'dark') {
      document.body.classList.add('dark-theme');
      localStorage.setItem('admin_theme', 'dark');
    } else {
      document.body.classList.remove('dark-theme');
      localStorage.setItem('admin_theme', 'light');
    }
  };

  // Tab: Activity Log
  const [logs] = useState([
    { id: 1, action: 'Login', desc: 'Admin logged in successfully', time: 'Apr 25, 2026 10:30 AM', ip: '192.168.1.10' },
    { id: 2, action: 'Sync', desc: 'Triggered city vitals sync', time: 'Apr 25, 2026 10:35 AM', ip: '192.168.1.10' },
    { id: 3, action: 'Export', desc: 'Downloaded traffic CSV report', time: 'Apr 25, 2026 09:45 AM', ip: '192.168.1.10' },
    { id: 4, action: 'User Added', desc: 'Added new admin John Doe', time: 'Apr 24, 2026 03:00 PM', ip: '192.168.1.10' },
    { id: 5, action: 'Settings', desc: 'Updated notification settings', time: 'Apr 24, 2026 01:00 PM', ip: '192.168.1.10' },
    { id: 6, action: 'Login', desc: 'Admin logged in successfully', time: 'Apr 24, 2026 09:00 AM', ip: '192.168.1.11' },
    { id: 7, action: 'Password', desc: 'Password changed successfully', time: 'Apr 23, 2026 05:30 PM', ip: '192.168.1.10' },
    { id: 8, action: 'Report', desc: 'Generated Zone B traffic report', time: 'Apr 23, 2026 03:15 PM', ip: '192.168.1.10' },
    { id: 9, action: 'Logout', desc: 'Admin logged out', time: 'Apr 23, 2026 06:00 PM', ip: '192.168.1.10' },
    { id: 10, action: 'Login', desc: 'Admin logged in successfully', time: 'Apr 23, 2026 09:10 AM', ip: '192.168.1.10' }
  ]);

  const exportLogPDF = () => {
    setLoading(true);
    const doc = new jsPDF();
    doc.setFontSize(20);
    doc.setTextColor(37, 99, 235);
    doc.text("Admin Activity Log Report", 14, 22);
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text(`Generated On: April 25, 2026 — 10:45 AM`, 14, 30);
    doc.text(`Generated By: ${profile.name}`, 14, 35);
    doc.autoTable({
      head: [['#', 'Action', 'Description', 'Date & Time', 'IP Address']],
      body: logs.map((l, i) => [i + 1, l.action, l.desc, l.time, l.ip]),
      startY: 45,
      theme: 'grid',
      headStyles: { fillColor: [37, 99, 235] },
      alternateRowStyles: { fillColor: [245, 247, 250] },
      styles: { fontSize: 8 }
    });
    doc.setFontSize(9);
    doc.setTextColor(150);
    doc.text("Smart City System — Confidential Activity Log", 14, doc.internal.pageSize.height - 10);
    doc.save('admin_activity_log_april2026.pdf');
    setLoading(false);
    alert('PDF exported successfully');
  };

  const exportProfilePDF = () => {
    setLoading(true);
    const doc = new jsPDF();
    doc.setFontSize(22);
    doc.setTextColor(37, 99, 235);
    doc.text("Admin Profile Report", 14, 25);
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text(`Generated On: April 25, 2026`, 14, 35);
    
    const content = [
      ["Full Name", profile.name],
      ["Username", profile.username],
      ["Email Address", profile.email],
      ["Phone Number", profile.phone],
      ["Role", profile.role],
      ["Department", profile.dept],
      ["Employee ID", profile.empId],
      ["Joined Date", profile.joined],
      ["Last Login", profile.lastLogin],
      ["Status", profile.status]
    ];
    
    doc.autoTable({
      body: content,
      startY: 45,
      theme: 'plain',
      styles: { fontSize: 11, cellPadding: 5 },
      columnStyles: { 0: { fontStyle: 'bold', width: 50 } }
    });
    
    doc.setFontSize(9);
    doc.setTextColor(150);
    doc.text("Smart City System — Admin Profile Report", 14, doc.internal.pageSize.height - 10);
    doc.save('admin_profile_report.pdf');
    setLoading(false);
    alert('PDF exported successfully');
  };

  const exportSettingsPDF = () => {
    setLoading(true);
    const doc = new jsPDF();
    doc.setFontSize(22);
    doc.setTextColor(37, 99, 235);
    doc.text("Account Settings Report", 14, 25);
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text(`Generated On: April 25, 2026`, 14, 35);
    
    const content = [
      ["Language", settings.lang],
      ["Timezone", settings.timezone],
      ["Notification Alerts", settings.notifications ? "Enabled" : "Disabled"],
      ["Email Notifications", settings.emailAlerts ? "Enabled" : "Disabled"],
      ["SMS Alerts", settings.smsAlerts ? "Enabled" : "Disabled"],
      ["Two Factor Auth", settings.twoFactor ? "Enabled" : "Disabled"],
      ["Dashboard Theme", settings.theme === 'light' ? 'Light Mode' : 'Dark Mode'],
      ["Session Timeout", settings.timeout]
    ];
    
    doc.autoTable({
      body: content,
      startY: 45,
      theme: 'grid',
      styles: { fontSize: 11, cellPadding: 5 },
      headStyles: { fillColor: [37, 99, 235] },
      columnStyles: { 0: { fontStyle: 'bold', fillColor: [245, 247, 250] } }
    });
    
    doc.setFontSize(9);
    doc.setTextColor(150);
    doc.text("Smart City System — Account Settings Report", 14, doc.internal.pageSize.height - 10);
    doc.save('account_settings_report.pdf');
    setLoading(false);
    alert('PDF exported successfully');
  };

  return (
    <div className="container-fluid p-0">
      {loading && (
        <div className="side-panel-overlay d-flex align-items-center justify-content-center" style={{background: 'rgba(255,255,255,0.7)', zIndex: 9999}}>
          <div className="spinner-border text-primary" role="status"></div>
        </div>
      )}

      {/* EDIT PROFILE MODAL */}
      {showEditProfile && (
        <div className="side-panel-overlay" onClick={() => setShowEditProfile(false)}>
          <div className="side-panel" onClick={e => e.stopPropagation()} style={{width: '500px'}}>
            <div className="side-panel-header">
              <h5 className="mb-0 fw-800">Edit Admin Profile</h5>
              <button className="btn-close" onClick={() => setShowEditProfile(false)}></button>
            </div>
            <div className="side-panel-body">
              <div className="text-center mb-4">
                <div className="topbar-avatar mx-auto mb-2" style={{width: '70px', height: '70px', background: 'linear-gradient(135deg, #10B981, #3B82F6)'}}>{editForm.name.charAt(0)}</div>
                <button className="btn btn-sm btn-outline-primary">Upload New Photo</button>
              </div>
              <div className="mb-3">
                <label className="detail-label">Full Name</label>
                <input type="text" className="input-smart" value={editForm.name} onChange={e => setEditForm({...editForm, name: e.target.value})} />
              </div>
              <div className="mb-3">
                <label className="detail-label">Username</label>
                <input type="text" className="input-smart" value={editForm.username} onChange={e => setEditForm({...editForm, username: e.target.value})} />
              </div>
              <div className="mb-3">
                <label className="detail-label">Email Address</label>
                <input type="email" className="input-smart" value={editForm.email} onChange={e => setEditForm({...editForm, email: e.target.value})} />
              </div>
              <div className="mb-3">
                <label className="detail-label">Phone Number</label>
                <input type="text" className="input-smart" value={editForm.phone} onChange={e => setEditForm({...editForm, phone: e.target.value})} />
              </div>
              <div className="mb-3">
                <label className="detail-label">Department</label>
                <input type="text" className="input-smart" value={editForm.dept} onChange={e => setEditForm({...editForm, dept: e.target.value})} />
              </div>
            </div>
            <div className="side-panel-footer d-flex gap-2">
              <button className="btn btn-outline-secondary flex-grow-1" onClick={() => setShowEditProfile(false)}>Cancel</button>
              <button className="btn btn-primary flex-grow-1" onClick={handleSaveProfile}>Save Changes</button>
            </div>
          </div>
        </div>
      )}

      <div className="row g-4">
        <div className="col-md-3">
          <div className="card-smart p-0 overflow-hidden">
            <div className="p-4 text-center border-bottom bg-light">
              <div className="topbar-avatar mx-auto mb-3" style={{width: '80px', height: '80px', fontSize: '32px', background: 'linear-gradient(135deg, #10B981, #3B82F6)'}}>{profile.name.charAt(0)}</div>
              <h5 className="fw-800 mb-0">{profile.name}</h5>
              <div className="text-muted small uppercase letter-spacing-1">{profile.role}</div>
            </div>
            <div className="p-2">
              {[
                { id: 'profile', label: '👤 My Profile' },
                { id: 'account', label: '⚙️ Account Settings' },
                { id: 'password', label: '🔒 Change Password' },
                { id: 'log', label: '📋 Activity Log' }
              ].map(tab => (
                <button 
                  key={tab.id}
                  className={`btn w-100 text-start border-0 py-3 px-4 rounded mb-1 cursor-pointer ${activeTab === tab.id ? 'btn-primary-smart' : 'btn-light text-dark'}`}
                  onClick={() => setActiveTab(tab.id)}
                >
                  {tab.label}
                </button>
              ))}
            </div>
          </div>
        </div>

        <div className="col-md-9">
          <div className="card-smart h-100">
            {activeTab === 'profile' && (
              <div className="animate-fade-in">
                <div className="d-flex justify-content-between align-items-center mb-4">
                  <h4 className="fw-800 mb-0">My Profile</h4>
                  <div className="d-flex gap-2">
                    <button className="btn-smart btn-outline-smart py-2 cursor-pointer" onClick={exportProfilePDF}>📄 Export Profile PDF</button>
                    <button className="btn-smart btn-outline-smart py-2 cursor-pointer" onClick={() => { setEditForm({...profile}); setShowEditProfile(true); }}>Edit Profile</button>
                  </div>
                </div>
                <div className="row g-4">
                  {[
                    { label: 'Full Name', value: profile.name },
                    { label: 'Username', value: profile.username },
                    { label: 'Email Address', value: profile.email },
                    { label: 'Phone Number', value: profile.phone },
                    { label: 'Department', value: profile.dept },
                    { label: 'Employee ID', value: profile.empId },
                    { label: 'Joined Date', value: profile.joined },
                    { label: 'Last Login', value: profile.lastLogin },
                    { label: 'Status', value: profile.status, color: 'success' }
                  ].map((field, i) => (
                    <div key={i} className="col-md-6">
                      <div className="detail-label">{field.label}</div>
                      <div className={`detail-value ${field.color ? `text-${field.color} fw-800` : ''}`}>{field.value}</div>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {activeTab === 'account' && (
              <div className="animate-fade-in">
                <div className="d-flex justify-content-between align-items-center mb-4">
                  <h4 className="fw-800 mb-0">Account Settings</h4>
                  <button className="btn-smart btn-outline-smart py-2 cursor-pointer" onClick={exportSettingsPDF}>📄 Export Settings PDF</button>
                </div>
                <div className="row g-4">
                  <div className="col-md-6">
                    <label className="detail-label">Language</label>
                    <select className="select-smart cursor-pointer"><option>{settings.lang}</option></select>
                  </div>
                  <div className="col-md-6">
                    <label className="detail-label">Timezone</label>
                    <select className="select-smart cursor-pointer"><option>{settings.timezone}</option></select>
                  </div>
                  <div className="col-md-6">
                    <div className="d-flex justify-content-between align-items-center p-3 border rounded hover-bg-light cursor-pointer">
                      <div>
                        <div className="fw-bold">Notification Alerts</div>
                        <div className="text-muted xx-small">Enable push notifications for system events</div>
                      </div>
                      <div className="form-check form-switch"><input className="form-check-input cursor-pointer" type="checkbox" checked={settings.notifications} onChange={e => setSettings({...settings, notifications: e.target.checked})} /></div>
                    </div>
                  </div>
                  <div className="col-md-6">
                    <div className="d-flex justify-content-between align-items-center p-3 border rounded hover-bg-light cursor-pointer">
                      <div>
                        <div className="fw-bold">Email Notifications</div>
                        <div className="text-muted xx-small">Receive daily summaries via email</div>
                      </div>
                      <div className="form-check form-switch"><input className="form-check-input cursor-pointer" type="checkbox" checked={settings.emailAlerts} onChange={e => setSettings({...settings, emailAlerts: e.target.checked})} /></div>
                    </div>
                  </div>
                  <div className="col-md-6">
                    <label className="detail-label">Dashboard Theme</label>
                    <div className="d-flex gap-2">
                      <button className={`btn flex-grow-1 cursor-pointer ${settings.theme === 'light' ? 'btn-primary' : 'btn-outline-secondary'}`} onClick={() => toggleTheme('light')}>Light Mode 🌤️</button>
                      <button className={`btn flex-grow-1 cursor-pointer ${settings.theme === 'dark' ? 'btn-primary' : 'btn-outline-secondary'}`} onClick={() => toggleTheme('dark')}>Dark Mode 🌙</button>
                    </div>
                  </div>
                  <div className="col-md-12 mt-5">
                    <button className="btn-smart btn-primary-smart px-5 cursor-pointer" onClick={handleSaveSettings}>Save All Changes</button>
                  </div>
                </div>
              </div>
            )}

            {activeTab === 'password' && (
              <div className="animate-fade-in" style={{maxWidth: '500px'}}>
                <h4 className="fw-800 mb-4">Change Password</h4>
                <div className="alert alert-info py-2 small">
                  Password must be at least 8 characters long, include 1 uppercase, 1 number, and 1 special character.
                </div>
                <div className="mb-3">
                  <label className="detail-label">Current Password</label>
                  <input type="password" className="input-smart" placeholder="••••••••" />
                </div>
                <div className="mb-3">
                  <label className="detail-label">New Password</label>
                  <input type="password" className="input-smart" placeholder="••••••••" />
                </div>
                <div className="mb-4">
                  <label className="detail-label">Confirm New Password</label>
                  <input type="password" className="input-smart" placeholder="••••••••" />
                </div>
                <button className="btn-smart btn-primary-smart w-100 cursor-pointer">Update Password</button>
              </div>
            )}

            {activeTab === 'log' && (
              <div className="animate-fade-in">
                <div className="d-flex justify-content-between align-items-center mb-4">
                  <h4 className="fw-800 mb-0">Activity Log</h4>
                  <button className="btn-smart btn-outline-smart cursor-pointer" onClick={exportLogPDF}>📄 Export Log PDF</button>
                </div>
                <div className="table-responsive">
                  <table className="table-smart">
                    <thead>
                      <tr>
                        <th>#</th>
                        <th>Action</th>
                        <th>Description</th>
                        <th>Date & Time</th>
                        <th>IP Address</th>
                      </tr>
                    </thead>
                    <tbody>
                      {logs.map((l, i) => (
                        <tr key={l.id}>
                          <td>{i+1}</td>
                          <td><span className="badge-status badge-info">{l.action}</span></td>
                          <td className="small">{l.desc}</td>
                          <td className="text-muted xx-small">{l.time}</td>
                          <td className="font-monospace xx-small">{l.ip}</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
