import { useState } from 'react';
import jsPDF from 'jspdf';
import 'jspdf-autotable';

export default function AdminInbox() {
  const [search, setSearch] = useState('');
  const [filter, setFilter] = useState('All');
  const [currentPage, setCurrentPage] = useState(1);
  const [loading, setLoading] = useState(false);
  const itemsPerPage = 10;

  const [messages, setMessages] = useState([
    { id: 1, sender: 'Admin', msg: 'Please review the latest city report', time: '5 mins ago', status: 'Unread' },
    { id: 2, sender: 'System Bot', msg: 'Your export is ready to download', time: '20 mins ago', status: 'Read' },
    { id: 3, sender: 'Support', msg: 'Your ticket #1023 has been resolved', time: '1 hour ago', status: 'Read' },
    { id: 4, sender: 'Manager', msg: 'Update the traffic data before EOD', time: 'Yesterday', status: 'Read' },
    { id: 5, sender: 'Admin', msg: 'New city zone data has been uploaded', time: '2 days ago', status: 'Read' },
    { id: 6, sender: 'System Bot', msg: 'Scheduled backup completed successfully', time: '3 days ago', status: 'Read' },
    { id: 7, sender: 'Support', msg: 'Ticket #1019 requires your attention', time: '4 days ago', status: 'Unread' },
    { id: 8, sender: 'Manager', msg: 'Q3 traffic analysis report is due', time: '5 days ago', status: 'Read' },
    { id: 9, sender: 'Security', msg: 'System integrity check passed', time: '6 days ago', status: 'Read' },
    { id: 10, sender: 'HR', msg: 'New administrative policies updated', time: '1 week ago', status: 'Read' }
  ]);

  const filteredMessages = messages.filter(m => {
    const matchesSearch = m.sender.toLowerCase().includes(search.toLowerCase()) || m.msg.toLowerCase().includes(search.toLowerCase());
    const matchesFilter = filter === 'All' || m.status === filter;
    return matchesSearch && matchesFilter;
  });

  const totalPages = Math.ceil(filteredMessages.length / itemsPerPage);
  const paginatedMessages = filteredMessages.slice((currentPage - 1) * itemsPerPage, currentPage * itemsPerPage);

  const handleExportPDF = () => {
    setLoading(true);
    const doc = new jsPDF();
    doc.setFontSize(20);
    doc.setTextColor(37, 99, 235);
    doc.text("Inbox Messages Report", 14, 22);
    
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text(`Generated On: April 25, 2026 — 10:45 AM`, 14, 30);
    doc.text(`Generated By: Admin User`, 14, 35);
    doc.text(`Platform: Smart City System`, 14, 40);

    doc.autoTable({
      head: [['#', 'Sender', 'Message', 'Time', 'Status']],
      body: filteredMessages.map((m, i) => [i + 1, m.sender, m.msg, m.time, m.status]),
      startY: 45,
      theme: 'grid',
      headStyles: { fillColor: [37, 99, 235] },
      alternateRowStyles: { fillColor: [245, 247, 250] },
      didParseCell: (data) => {
        if (data.column.index === 4 && data.section === 'body' && data.cell.raw === 'Unread') {
          data.row.cells.forEach(c => {
            c.styles.fontStyle = 'bold';
            c.styles.fillColor = [235, 245, 255];
          });
        }
      }
    });

    doc.save('inbox_messages_report_april2026.pdf');
    setLoading(false);
    alert('PDF exported successfully');
  };

  const clearUnread = () => {
    setMessages(messages.map(m => ({ ...m, status: 'Read' })));
    alert('All messages marked as read');
  };

  return (
    <div className="container-fluid p-0">
      {loading && (
        <div className="side-panel-overlay d-flex align-items-center justify-content-center" style={{background: 'rgba(255,255,255,0.7)', zIndex: 9999}}>
          <div className="spinner-border text-primary" role="status"></div>
        </div>
      )}
      <div className="card-smart">
        <div className="d-flex justify-content-between align-items-center mb-4">
          <h4 className="fw-800 text-primary mb-0">📩 Administrative Inbox</h4>
          <div className="d-flex gap-2">
            <button className="btn-smart btn-outline-smart py-2 cursor-pointer" onClick={clearUnread}>Clear Unread</button>
            <button className="btn-smart btn-primary-smart py-2 cursor-pointer" onClick={handleExportPDF}>📄 Export PDF</button>
          </div>
        </div>

        <div className="row g-3 mb-4">
          <div className="col-md-6">
            <input 
              type="text" 
              className="input-smart" 
              placeholder="Search by sender or content..." 
              value={search}
              onChange={(e) => { setSearch(e.target.value); setCurrentPage(1); }}
            />
          </div>
          <div className="col-md-6 text-end">
            <div className="btn-group shadow-sm rounded overflow-hidden">
              {['All', 'Unread', 'Read'].map(f => (
                <button 
                  key={f}
                  className={`btn py-2 px-4 border-0 cursor-pointer ${filter === f ? 'btn-primary' : 'btn-light text-muted'}`}
                  onClick={() => { setFilter(f); setCurrentPage(1); }}
                >
                  {f}
                </button>
              ))}
            </div>
          </div>
        </div>

        <div className="table-responsive">
          <table className="table-smart">
            <thead>
              <tr>
                <th>#</th>
                <th>Sender</th>
                <th>Message Content</th>
                <th>Timestamp</th>
                <th>Status</th>
              </tr>
            </thead>
            <tbody>
              {paginatedMessages.map((m, idx) => (
                <tr key={m.id} className={m.status === 'Unread' ? 'bg-light' : ''}>
                  <td className="text-muted fw-bold">{(currentPage - 1) * itemsPerPage + idx + 1}</td>
                  <td><span className={m.status === 'Unread' ? 'fw-800 text-dark' : 'text-dark'}>{m.sender}</span></td>
                  <td style={{maxWidth: '400px'}} className={m.status === 'Unread' ? 'fw-600' : ''}>{m.msg}</td>
                  <td className="text-muted small">{m.time}</td>
                  <td>
                    <span className={`badge-status ${m.status === 'Unread' ? 'badge-danger' : 'badge-success'}`}>
                      {m.status}
                    </span>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {totalPages > 1 && (
          <div className="d-flex justify-content-between align-items-center mt-4">
            <div className="text-muted small">Showing {paginatedMessages.length} of {filteredMessages.length} messages</div>
            <div className="d-flex gap-2">
              <button 
                className="btn-smart btn-outline-smart py-1 px-3 cursor-pointer" 
                disabled={currentPage === 1}
                onClick={() => setCurrentPage(prev => prev - 1)}
              >
                Previous
              </button>
              <button 
                className="btn-smart btn-outline-smart py-1 px-3 cursor-pointer" 
                disabled={currentPage === totalPages}
                onClick={() => setCurrentPage(prev => prev + 1)}
              >
                Next
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
