import { useState } from 'react';
import jsPDF from 'jspdf';
import 'jspdf-autotable';

export default function AdminActivityLog() {
  const [search, setSearch] = useState('');
  const [filter, setFilter] = useState('All');
  const [currentPage, setCurrentPage] = useState(1);
  const [loading, setLoading] = useState(false);
  const itemsPerPage = 10;

  const [logs, setLogs] = useState([
    { id: 1, type: 'Success', title: 'System Sync', desc: 'City vitals synchronized successfully', time: 'Apr 25, 10:43 AM', status: 'Read' },
    { id: 2, type: 'Error', title: 'Sync Error', desc: 'Failed to synchronize city vitals', time: 'Apr 25, 10:35 AM', status: 'Unread' },
    { id: 3, type: 'Info', title: 'Report Ready', desc: 'Traffic CSV report generated', time: 'Apr 25, 09:45 AM', status: 'Read' },
    { id: 4, type: 'Warning', title: 'Maintenance', desc: 'System maintenance scheduled at 12:00 AM', time: 'Apr 25, 07:45 AM', status: 'Unread' },
    { id: 5, type: 'Info', title: 'New Admin', desc: 'New admin user added: John Doe', time: 'Apr 24, 03:00 PM', status: 'Read' },
    { id: 6, type: 'Success', title: 'Data Upload', desc: 'New city zone data uploaded successfully', time: 'Apr 24, 01:00 PM', status: 'Read' },
    { id: 7, type: 'Error', title: 'API Failure', desc: 'City weather API failed to respond', time: 'Apr 23, 11:00 AM', status: 'Read' },
    { id: 8, type: 'Warning', title: 'Storage Alert', desc: 'Server storage usage exceeded 85%', time: 'Apr 23, 09:00 AM', status: 'Unread' },
    { id: 9, type: 'Success', title: 'Backup Done', desc: 'Scheduled system backup completed', time: 'Apr 22, 06:00 PM', status: 'Read' },
    { id: 10, type: 'Info', title: 'User Login', desc: 'Admin logged in from new device', time: 'Apr 22, 09:10 AM', status: 'Read' }
  ]);

  const filteredLogs = logs.filter(l => {
    const matchesSearch = l.title.toLowerCase().includes(search.toLowerCase()) || l.desc.toLowerCase().includes(search.toLowerCase());
    const matchesFilter = filter === 'All' || l.status === filter;
    return matchesSearch && matchesFilter;
  });

  const totalPages = Math.ceil(filteredLogs.length / itemsPerPage);
  const paginatedLogs = filteredLogs.slice((currentPage - 1) * itemsPerPage, currentPage * itemsPerPage);

  const handleExportPDF = () => {
    setLoading(true);
    const doc = new jsPDF();
    doc.setFontSize(20);
    doc.setTextColor(37, 99, 235);
    doc.text("Notifications Report", 14, 22);
    
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text(`Generated On: April 25, 2026 — 10:45 AM`, 14, 30);
    doc.text(`Generated By: Admin User`, 14, 35);
    doc.text(`Platform: Smart City System`, 14, 40);

    doc.autoTable({
      head: [['#', 'Type', 'Title', 'Description', 'Time', 'Status']],
      body: filteredLogs.map((l, i) => [i + 1, l.type.toUpperCase(), l.title, l.desc, l.time, l.status]),
      startY: 45,
      theme: 'grid',
      headStyles: { fillColor: [37, 99, 235] },
      alternateRowStyles: { fillColor: [245, 247, 250] },
      didParseCell: (data) => {
        if (data.column.index === 1 && data.section === 'body') {
          const val = data.cell.raw;
          if (val === 'SUCCESS') data.cell.styles.textColor = [16, 185, 129];
          if (val === 'ERROR') data.cell.styles.textColor = [239, 68, 68];
          if (val === 'WARNING') data.cell.styles.textColor = [245, 158, 11];
          if (val === 'INFO') data.cell.styles.textColor = [37, 99, 235];
          data.cell.styles.fontStyle = 'bold';
        }
      }
    });

    doc.setFontSize(9);
    doc.setTextColor(150);
    doc.text("Smart City System — Confidential Notifications Report", 14, doc.internal.pageSize.height - 10);
    doc.save('notifications_report_april2026.pdf');
    setLoading(false);
    alert('PDF exported successfully');
  };

  const markAllRead = () => {
    setLogs(logs.map(l => ({ ...l, status: 'Read' })));
    alert('All notifications marked as read');
  };

  return (
    <div className="container-fluid p-0">
      {loading && (
        <div className="side-panel-overlay d-flex align-items-center justify-content-center" style={{background: 'rgba(255,255,255,0.7)', zIndex: 9999}}>
          <div className="spinner-border text-primary" role="status"></div>
        </div>
      )}
      <div className="card-smart">
        <div className="d-flex justify-content-between align-items-center mb-4">
          <h4 className="fw-800 text-primary mb-0">🔔 System Activity Log</h4>
          <div className="d-flex gap-2">
            <button className="btn-smart btn-outline-smart py-2 cursor-pointer" onClick={markAllRead}>Mark All Read</button>
            <button className="btn-smart btn-primary-smart py-2 cursor-pointer" onClick={handleExportPDF}>📄 Export PDF</button>
          </div>
        </div>

        <div className="row g-3 mb-4">
          <div className="col-md-6">
            <input 
              type="text" 
              className="input-smart" 
              placeholder="Search by title or description..." 
              value={search}
              onChange={(e) => { setSearch(e.target.value); setCurrentPage(1); }}
            />
          </div>
          <div className="col-md-6 text-end">
            <div className="btn-group shadow-sm rounded overflow-hidden">
              {['All', 'Unread', 'Read'].map(f => (
                <button 
                  key={f}
                  className={`btn py-2 px-4 border-0 cursor-pointer ${filter === f ? 'btn-primary' : 'btn-light text-muted'}`}
                  onClick={() => { setFilter(f); setCurrentPage(1); }}
                >
                  {f}
                </button>
              ))}
            </div>
          </div>
        </div>

        <div className="table-responsive">
          <table className="table-smart">
            <thead>
              <tr>
                <th>#</th>
                <th>Type</th>
                <th>Event Title</th>
                <th>Description</th>
                <th>Timestamp</th>
                <th>Status</th>
              </tr>
            </thead>
            <tbody>
              {paginatedLogs.map((l, idx) => (
                <tr key={l.id}>
                  <td className="text-muted fw-bold">{(currentPage - 1) * itemsPerPage + idx + 1}</td>
                  <td>
                    <span className={`badge-status fw-800 uppercase`} style={{fontSize: '10px', color: l.type === 'Success' ? '#10B981' : l.type === 'Error' ? '#EF4444' : l.type === 'Warning' ? '#F59E0B' : '#2563EB'}}>
                      {l.type}
                    </span>
                  </td>
                  <td><span className="fw-bold text-dark">{l.title}</span></td>
                  <td className="small">{l.desc}</td>
                  <td className="text-muted small">{l.time}</td>
                  <td>
                    <span className={`fw-600 small ${l.status === 'Unread' ? 'text-danger' : 'text-success'}`}>
                      {l.status === 'Unread' ? '● Unread' : '✓ Read'}
                    </span>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {totalPages > 1 && (
          <div className="d-flex justify-content-between align-items-center mt-4">
            <div className="text-muted small">Showing {paginatedLogs.length} of {filteredLogs.length} events</div>
            <div className="d-flex gap-2">
              <button 
                className="btn-smart btn-outline-smart py-1 px-3 cursor-pointer" 
                disabled={currentPage === 1}
                onClick={() => setCurrentPage(prev => prev - 1)}
              >
                Previous
              </button>
              <button 
                className="btn-smart btn-outline-smart py-1 px-3 cursor-pointer" 
                disabled={currentPage === totalPages}
                onClick={() => setCurrentPage(prev => prev + 1)}
              >
                Next
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
