import { useState } from 'react';
import jsPDF from 'jspdf';
import 'jspdf-autotable';

export default function UserActivityLog() {
  const [search, setSearch] = useState('');
  const [filter, setFilter] = useState('All');
  const [currentPage, setCurrentPage] = useState(1);
  const [loading, setLoading] = useState(false);
  const itemsPerPage = 10;

  const [logs, setLogs] = useState([
    { id: 1, action: 'Register', desc: 'Account created successfully', time: 'Apr 25, 10:00 AM', ip: '192.168.1.15' },
    { id: 2, action: 'Login', desc: 'Logged in successfully', time: 'Apr 25, 10:05 AM', ip: '192.168.1.15' },
    { id: 3, action: 'Profile', desc: 'Updated profile information', time: 'Apr 25, 10:10 AM', ip: '192.168.1.15' },
    { id: 4, action: 'Message', desc: 'Sent reply to Admin', time: 'Apr 25, 10:15 AM', ip: '192.168.1.15' },
    { id: 5, action: 'Report', desc: 'Viewed city zone report', time: 'Apr 25, 10:20 AM', ip: '192.168.1.15' },
    { id: 6, action: 'Settings', desc: 'Updated notification settings', time: 'Apr 24, 03:00 PM', ip: '192.168.1.15' },
    { id: 7, action: 'Password', desc: 'Password changed successfully', time: 'Apr 24, 01:00 PM', ip: '192.168.1.15' },
    { id: 8, action: 'Login', desc: 'Logged in from new device', time: 'Apr 23, 09:00 AM', ip: '192.168.1.16' },
    { id: 9, action: 'Logout', desc: 'Logged out successfully', time: 'Apr 23, 06:00 PM', ip: '192.168.1.15' },
    { id: 10, action: 'Login', desc: 'Logged in successfully', time: 'Apr 23, 08:50 AM', ip: '192.168.1.15' }
  ]);

  const filteredLogs = logs.filter(l => {
    const matchesSearch = l.action.toLowerCase().includes(search.toLowerCase()) || l.desc.toLowerCase().includes(search.toLowerCase());
    const matchesFilter = filter === 'All' || l.action === filter;
    return matchesSearch && matchesFilter;
  });

  const totalPages = Math.ceil(filteredLogs.length / itemsPerPage);
  const paginatedLogs = filteredLogs.slice((currentPage - 1) * itemsPerPage, currentPage * itemsPerPage);

  const handleExportPDF = () => {
    setLoading(true);
    const doc = new jsPDF();
    doc.setFontSize(20);
    doc.setTextColor(37, 99, 235);
    doc.text("User Activity Log Report", 14, 22);
    
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text(`Generated On: ${new Date().toLocaleString()}`, 14, 30);
    doc.text(`Generated By: ${localStorage.getItem('username') || 'User'}`, 14, 35);
    doc.text(`Smart City System — Confidential User Report`, 14, 40);

    doc.autoTable({
      head: [['#', 'Action', 'Description', 'Date & Time', 'IP Address']],
      body: filteredLogs.map((l, i) => [i + 1, l.action, l.desc, l.time, l.ip]),
      startY: 50,
      theme: 'grid',
      headStyles: { fillColor: [37, 99, 235] },
      alternateRowStyles: { fillColor: [245, 247, 250] },
      styles: { fontSize: 9 }
    });

    doc.save('user_activity_log_report.pdf');
    setLoading(false);
    alert('PDF exported successfully');
  };

  return (
    <div className="container-fluid p-0">
      {loading && (
        <div className="side-panel-overlay d-flex align-items-center justify-content-center" style={{background: 'rgba(255,255,255,0.7)', zIndex: 9999}}>
          <div className="spinner-border text-primary" role="status"></div>
        </div>
      )}
      <div className="card-smart">
        <div className="d-flex justify-content-between align-items-center mb-4">
          <h4 className="fw-800 text-primary mb-0">📋 My Activity Log</h4>
          <button className="btn-smart btn-primary-smart py-2 cursor-pointer" onClick={handleExportPDF}>📄 Export PDF</button>
        </div>

        <div className="row g-3 mb-4">
          <div className="col-md-6">
            <input 
              type="text" 
              className="input-smart" 
              placeholder="Search actions or descriptions..." 
              value={search}
              onChange={(e) => { setSearch(e.target.value); setCurrentPage(1); }}
            />
          </div>
          <div className="col-md-6 text-end">
            <select className="input-smart d-inline-block w-auto" value={filter} onChange={(e) => { setFilter(e.target.value); setCurrentPage(1); }}>
              <option value="All">All Actions</option>
              <option value="Login">Login</option>
              <option value="Logout">Logout</option>
              <option value="Profile">Profile Update</option>
              <option value="Password">Password Change</option>
              <option value="Message">Messaging</option>
            </select>
          </div>
        </div>

        <div className="table-responsive">
          <table className="table-smart">
            <thead>
              <tr>
                <th>#</th>
                <th>Action</th>
                <th>Description</th>
                <th>Date & Time</th>
                <th>IP Address</th>
              </tr>
            </thead>
            <tbody>
              {paginatedLogs.map((l, idx) => (
                <tr key={l.id}>
                  <td className="text-muted fw-bold">{(currentPage - 1) * itemsPerPage + idx + 1}</td>
                  <td>
                    <span className="badge-status badge-info fw-800 uppercase" style={{fontSize: '10px'}}>
                      {l.action}
                    </span>
                  </td>
                  <td className="small">{l.desc}</td>
                  <td className="text-muted small">{l.time}</td>
                  <td className="font-monospace small">{l.ip}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {totalPages > 1 && (
          <div className="d-flex justify-content-between align-items-center mt-4">
            <div className="text-muted small">Showing {paginatedLogs.length} entries</div>
            <div className="d-flex gap-2">
              <button 
                className="btn-smart btn-outline-smart py-1 px-3 cursor-pointer" 
                disabled={currentPage === 1}
                onClick={() => setCurrentPage(prev => prev - 1)}
              >
                Previous
              </button>
              <button 
                className="btn-smart btn-outline-smart py-1 px-3 cursor-pointer" 
                disabled={currentPage === totalPages}
                onClick={() => setCurrentPage(prev => prev + 1)}
              >
                Next
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
